### ISSUE TITLE
systemd-analyze wouldn't run on sysVinit systems like MX Linux

### ISSUE THREAD

**Issue by amstelchen** [amstelchen/dblame#1]
```
$ dblame 
Traceback (most recent call last):
  File "/home/mic/.local/bin/dblame", line 8, in <module>
    sys.exit(main())
  File "/home/mic/.local/lib/python3.7/site-packages/dblame/__main__.py", line 81, in main
    total_time = time_items[-2]
IndexError: list index out of range

$ systemd-analyze 
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Der Rechner ist nicht aktiv

$ systemd-analyze --version
systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

**Comment by amstelchen** [comment]
Solved by checking `init --version`
