### ISSUE TITLE
systemd-analyze does not exist on BSD-style/sysVinit systems like Slackware

### ISSUE THREAD

**Issue by amstelchen** [amstelchen/dblame#2]
```
bash-5.1$ dblame
Traceback (most recent call last):
  File "/home/mic/.local/bin/dblame", line 8, in <module>
    sys.exit(main())
  File "/home/mic/.local/lib/python3.9/site-packages/dblame/__main__.py", line 58, in main
    sd_version = run(version.split(), capture_output=True).stdout.decode("utf-8")
  File "/usr/lib64/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'systemd-analyze'
```

**Comment by amstelchen** [comment]
Solved by checking `init --version`
